server.address=0.0.0.0
server.port=8080
spring.application.name=spb4you-backend

DB_HOST_VALUE=${DB_HOST:localhost}
DB_PORT_VALUE=${DB_PORT:5432}
DB_NAME_VALUE=${DB_NAME:postgres}
DB_USERNAME_VALUE=${DB_USERNAME:postgres}
DB_PASSWORD_VALUE=${DB_PASSWORD:svetapostgresql#666}

spring.datasource.url=jdbc:postgresql://${DB_HOST_VALUE}:${DB_PORT_VALUE}/${DB_NAME_VALUE}
spring.datasource.username=${DB_USERNAME_VALUE}
spring.datasource.password=${DB_PASSWORD_VALUE}
spring.datasource.driver-class-name=org.postgresql.Driver

CORS_ALLOWED_ORIGINS_VALUE=${CORS_ALLOWED_ORIGINS:http://localhost:3000}
CORS_ALLOW_CREDENTIALS_VALUE=${CORS_ALLOW_CREDENTIALS:true}

cors.allowed-origins=${CORS_ALLOWED_ORIGINS_VALUE}
cors.allow-credentials=${CORS_ALLOW_CREDENTIALS_VALUE}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.org.springframework=INFO